- hosts: db
  remote_user: jahmed
  become: yes
  tasks:
    - name: Install apache2 on the app server
      apt:
        name: apache2
        state: present
    - name: start apache2
      service: 
        name: apache2
        state: started
    - name: copy index file to app server
      copy:
        src: /home/jahmed/code/EDU-C1/playbooks/index.html
        dest: /var/www/html/index.html
        mode: 644
